### ISSUE TITLE
opam package coq-switch.1.0.1 cannot install anymore

### ISSUE THREAD

**Issue by clarus** [vzaliva/coq-switch#1]
Hi,

It seems that due to this pull-request: https://github.com/coq/opam-coq-archive/pull/1416 the package of `coq-switch` cannot install anymore. This is due to the dependency:
```
"coq-metacoq-template" {>= "1.0~alpha+8.9"}
```
which should now be `1.0~alpha1+8.9` or `1.0~alpha2+8.9`, I do not know.

Example of trace of error: https://coq-bench.github.io/clean/Linux-x86_64-4.11.1-2.0.7/released/8.11.2/switch/1.0.1.html
```
The following dependencies couldn't be met:
  - coq-switch -> coq-metacoq-template >= 1.0~alpha+8.9
      no matching version
No solution found, exiting
```

**Comment by vzaliva** [comment]
Sorry for the late reply. I am not sure where problems come from. I have coq-switch-1.0.2 installed via opam
with coq 8.11.2 and coq-metacoq-template 1.0~alpha2+8.11.

Can you try install coq-metacoq-template manually first?

**Comment by vzaliva** [comment]
For 1.0.2 it must be 1.0~alpha2+8.11. For 1.0.1 I am unsure, but it should be obsoleted. 
@clarus Should I upgrade OPAM file for 1.0.2?

**Comment by clarus** [comment]
I have not had the time to test it on my machine, but this pull-request seems to fix the issue, so closing. Thanks!
